### ISSUE TITLE
Marker pen doesn't render in correct colors

### ISSUE THREAD

**Issue by DavidValin** [Merovius/srvfb#11]
Love the poc!!!! i would love to use it for training. any plan to increase fps in the near future?

**Comment by Merovius** [comment]
No concrete plans, sorry. But mainly because I have no idea if it's possible or how I would even try :) One cause for the low FPS is lack of network bandwidth - when streaming over USB, the framerate is higher then when using wifi. But when I tried compressing frames, the framerate didn't improve, presumably because it costs too much CPU. In general, ISTM that the device is *super* under powered. You can also notice that when you upload files or open large documents in the ebook reader - those can take several minutes.

I had planned to actually profile the compression and everything to see if there are low-hanging fruit. And if you have any ideas for what to try, that'd be welcome. But for the most part, I have to admit that even with the low FPS it works for my use cases and I use it rarely enough that I'm not *super* incentivized to spend a lot of time on it.

**Comment by DavidValin** [comment]
Thanks Merovius... !! I don't think I can help with "go"... unfortunately, otherwise I would. You already did excellent, if it was a bit faster would be ideal for trainings or live conferences

**Comment by Merovius** [comment]
To clarify: Have you tried via both USB and WLAN? And is there a noticeable difference for you too? And if so, would it need to be a bit faster than USB or WLAN (and if the latter, would USB maybe even be enough :) )? Would give me an idea of what I'd have to shoot for.

**Comment by DavidValin** [comment]
I am connected via USB (SATECHI usb 2 convertor to my macbook pro) and using:
`ssh root@10.11.99.1 ./srvfb -device /dev/fb0 -listen :1234"`

I uploaded a gif in 25 fps. I think is the same as your twitter video
![ezgif-1-0b0cd79344d8](https://user-images.githubusercontent.com/841133/58704925-85d9d980-83a5-11e9-8563-ae7ec734f9b1.gif)

Also noted that the highlighting pen is 100% opaque and hides the black pen writings as it paints on top. Maybe would be better to render it behind the black pens, or with 0.5 opacity?

**Comment by Merovius** [comment]
Thanks, that's helpful :)

> Also noted that the highlighting pen is 100% opaque and hides the black pen writings as it paints on top. Maybe would be better to render it behind the black pens, or with 0.5 opacity?

This is an interesting observation, I have to try that out. I can't imagine why that is, we are simply grabbing what's on the screen, there shouldn't be any difference…

**Comment by Merovius** [comment]
Okay, so, I can definitely reproduce the marker-pen issue. The fps issue, I think, is just not super actionable right now. If it's okay with you, I'd close the fps-issue for now, but re-use this issue to track the marker-pen problem :)

**Comment by Merovius** [comment]
Okay, the marker-pen issue is a problem with endiannes: We are directly reading from the frame-buffer, which is 16 bit LittleEndian, but png assumes BigEndian, so the bytes end up swapped. Doesn't matter for black/white (as that's `0x0000` and `0xffff`), but matters for gray, which is `0x79ce`.

Unfortunate, as the conversion will make the framerate even lower :(
