### ISSUE TITLE
Nice idea, and I believe remarkable should update their own tools internally as well

### ISSUE THREAD

**Issue by andersnicolaimagnussen** [Merovius/srvfb#15]
I have tested it, but there is a big delay. Like 2-3 seconds. Which is very annoying. 
I understand you have created this in your free time for your own use case. But since you are using a remarkable how do you experience what I am experiencing. Is it fast for you?

**Comment by Merovius** [comment]
See [this closed issue](https://github.com/Merovius/srvfb/issues/13) for a little bit of a discussion about performance in general (tldr: Performance isn't great, but also, it doesn't bother me enough to put a lot of effort into it). That thread is primarily about throughput. Latency is, I think, in part for the same reason (if it takes 500ms to acquire and write a frame, this will also introduce some latency of course) and in part because we artificially introduce it by buffering a frame (due to idiosyncrasies of how chrome interprets the format we are streaming in). There are likely also other factors (e.g. I don't know whether the browser itself delays rendering maybe).

It could probably be improved significantly with enough work: For example, the suggestion to do manual compression and de-compression of frames instead of using M-JPEG might allow to get rid of the artificial delay, improve throughput *and* get rid of any format-specific rendering idiosyncrasies of the browser. But, as mentioned in #13 as well, I don't believe I will actually do that work for this project. I can live with both the delay and the low framerate for my usecase.
