### ISSUE TITLE
RGB streaming

### ISSUE THREAD

**Issue by ldecicco** [Merovius/srvfb#16]
First of all, thanks for the efforts. Very interesting for my usecase (using the remarkable instead of the blackboard for teaching). I would like to have an RGB streaming mode which is needed when annotating pdf slides. I would implement it myself but I am not proficient in go.

**Comment by Merovius** [comment]
I don't think this is possible. The reMarkable doesn't have a color-screen. We only have the framebuffer to work from and we copy that data verbatim (with the exception of a byte-swap for endianness). So we are already streaming all color information we have.

xiochitl could certainly interpret pen-strokes appropriately and then generate colored images. But that is something that would need to be added to their streaming features - it's not something that `srvfb` can do (and it is intentional that `srvfb` works that way).

I'll close this, but if I misunderstood what you want, feel free to clarify.

**Comment by ldecicco** [comment]
I didn't know the framebuffer was grayscale. If that's the case, of course there's nothing doable, other than changing the way the framebuffer works, which is out of the scope of this project of course.

**Comment by Merovius** [comment]
FYI, [someone chose a different approach to achieve something similar](https://www.reddit.com/r/golang/comments/azkv79/using_go_to_serve_input_detection_from_remarkable/). As far as I'm aware they didn't end up publishing their code yet, but they might if you hit them up. It also can't mirror PDFs (it just transfers your strokes to the computer), but it might be possible to add. The approach, in any case, is far more amenable to the extension you want, as the actual drawing doesn't happen on the device, so it can be in any color you like.

**Comment by ldecicco** [comment]
Thing is that I do not need the pen strokes to be colored, just need to retain the PDF (background) in color. Can you confirm the framebuffer is in black an white? Thanks a lot.

**Comment by Merovius** [comment]
The framebuffer is 16-bit grayscale.
